staging-settings:
  user-workflow:
    workflow-name: "cot-adjudicator"
    deployment-registry: "onchain:ethereum-mainnet"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "./secrets.yaml"
