import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("../../../../", import.meta.url).pathname;
const readme = readFileSync(root + "README.md", "utf8");
const full = (p) => { const m = readme.match(new RegExp(`transaction/(${p}[0-9a-f]{${64 - p.length}})`)); if (!m) throw new Error("no " + p); return m[1]; };
const run = (f) => JSON.parse(readFileSync(root + "agents/runs/" + f, "utf8"));
const rec = (r, step) => r.records.find((x) => x.step === step);
const a = run("2026-10-07T02-11-35-743Z.json"), b = run("2026-10-07T02-20-00-676Z.json");
const m = JSON.parse(readFileSync(new URL("./run-timeline.json", import.meta.url), "utf8"));
const P = {};
const add = (id, label, hash, source) => { P[id] = { label, txHash: hash, source }; };
add("delivers-lock", "Claim vault lock", rec(a, "claim_vault_lock").txHash, "agents/runs/2026-10-07T02-11-35-743Z.json");
add("delivers-pay", "Keeper A payment", rec(a, "seller-a_payment").txHash, "agents/runs/2026-10-07T02-11-35-743Z.json");
add("delivers-claim", "Keeper A claim", rec(a, "seller-a_claim").txHash, "agents/runs/2026-10-07T02-11-35-743Z.json");
add("stall-lock", "Claim vault lock", rec(b, "claim_vault_lock").txHash, "agents/runs/2026-10-07T02-20-00-676Z.json");
add("stall-payA", "Keeper A payment", rec(b, "seller-a_payment").txHash, "agents/runs/2026-10-07T02-20-00-676Z.json");
add("stall-payB", "Keeper B payment", rec(b, "seller-b_payment").txHash, "agents/runs/2026-10-07T02-20-00-676Z.json");
add("stall-claimB", "Keeper B claim", rec(b, "seller-b_claim").txHash, "agents/runs/2026-10-07T02-20-00-676Z.json");
add("race-lock", "Race lock", full("c0c104a07e"), "README.md");
add("race-payA", "Keeper A payment", full("e458925a99"), "README.md");
add("race-claimA", "Winning claim", full("43b27058c9"), "README.md");
add("race-payB", "Keeper B payment", full("aa40b41742"), "README.md");
add("cre-settle", "CRE coverage settlement", full("3e33929dbf"), "README.md");
add("trust-result", "Trust Check result hash", full("0be9fa229a"), "README.md");
const names = { "A escrow lock": "masumi-lockA", "B escrow lock": "masumi-lockB", "B ResultSubmitted": "masumi-resultB", "A refund request": "masumi-refundReq", "A refund withdrawn": "masumi-refundDone" };
for (const t of m.txs) add(names[t.role], t.role, t.txHash, m.source);
writeFileSync(new URL("./proofs.json", import.meta.url), JSON.stringify({ network: "preprod", explorer: "https://preprod.cardanoscan.io/transaction/", koios: "https://preprod.koios.rest/api/v1/tx_status", txs: P, races: { delivers: { checkpointAt: rec(a, "backup_not_needed").detail.checkpointAt, savedFeeAda: rec(a, "backup_not_needed").detail.savedFeeAda }, stall: { checkpointAt: rec(b, "backup_engaged").detail.checkpointAt, savedFeeAda: rec(b, "backup_engaged").detail.savedFeeAda } } }, null, 1));
console.log(Object.keys(P).length, Object.values(P).map((x) => x.txHash.slice(0, 8)).join(" "));
