// Copies the router core and the confirmed agent run records into web/ so a deploy
// rooted at web/ is self-contained. Runs before build; skips when the repo root is absent.
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const web = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repo = path.resolve(web, "..");
const routerDir = path.join(repo, "router");
const runsDir = path.join(repo, "agents", "runs");

if (!existsSync(routerDir) || !existsSync(runsDir)) {
  console.log("sync: repo root not present, using the committed copies in web/");
  process.exit(0);
}

const out = path.join(web, "src", "server", "router");
mkdirSync(out, { recursive: true });
for (const file of ["handler.ts", "routes.ts", "risk.ts"]) {
  const src = readFileSync(path.join(routerDir, "src", file), "utf8")
    .replaceAll('"../sellers.json"', '"./sellers.json"')
    .replaceAll('"../underwriter.json"', '"./underwriter.json"')
    .replace(/from "(\.\/[a-z]+)\.ts"/g, 'from "$1"');
  writeFileSync(path.join(out, file), `// GENERATED by web/scripts/sync.mjs from router/src/${file}. Edit the router, not this copy.\n${src}`);
}
for (const file of ["sellers.json", "underwriter.json"]) copyFileSync(path.join(routerDir, file), path.join(out, file));

const dest = path.join(web, "data", "runs");
rmSync(dest, { recursive: true, force: true });
mkdirSync(dest, { recursive: true });
let kept = 0;
for (const name of readdirSync(runsDir).filter((n) => n.endsWith(".json"))) {
  const raw = readFileSync(path.join(runsDir, name), "utf8");
  const records = JSON.parse(raw).records ?? [];
  if (records.some((r) => r.txHash && r.confirmed === true)) { writeFileSync(path.join(dest, name), raw); kept++; }
}
console.log(`sync: router core copied, ${kept} confirmed run records copied`);
