export type PlutusData =
  | { kind: "int"; value: number }
  | { kind: "bytes"; value: Uint8Array }
  | { kind: "list"; value: PlutusData[] }
  | { kind: "map"; value: [PlutusData, PlutusData][] }
  | { kind: "constr"; index: number; fields: PlutusData[] };

const hexBytes = (hex: string) => Uint8Array.from(hex.match(/../g)?.map((x) => parseInt(x, 16)) ?? []);
class Reader { constructor(readonly bytes: Uint8Array, public pos = 0) {} read() { if (this.pos >= this.bytes.length) throw new Error("cbor eof"); return this.bytes[this.pos++]; } take(n: number) { const end = this.pos + n; if (end > this.bytes.length) throw new Error("cbor eof"); const out = this.bytes.slice(this.pos, end); this.pos = end; return out; } }
const arg = (r: Reader, info: number): number => { if (info < 24) return info; const width = info === 24 ? 1 : info === 25 ? 2 : info === 26 ? 4 : info === 27 ? 8 : 0; if (!width) throw new Error("unsupported cbor argument"); let n = 0; for (let i = 0; i < width; i++) n = n * 256 + r.read(); if (!Number.isSafeInteger(n)) throw new Error("cbor integer is unsafe"); return n; };
const constr = (index: number, body: PlutusData): PlutusData => body.kind === "list" ? { kind: "constr", index, fields: body.value } : (() => { throw new Error("constructor body is not a list"); })();
const read = (r: Reader): PlutusData => { const h = r.read(); const major = h >> 5; const info = h & 31; if (major === 0) return { kind: "int", value: arg(r, info) }; if (major === 1) return { kind: "int", value: -1 - arg(r, info) }; if (major === 2) return { kind: "bytes", value: info === 31 ? (() => { const parts: Uint8Array[] = []; while (r.bytes[r.pos] !== 255) { const p = read(r); if (p.kind !== "bytes") throw new Error("invalid bytes chunk"); parts.push(p.value); } r.pos++; return parts.reduce((a, b) => { const out = new Uint8Array(a.length + b.length); out.set(a); out.set(b, a.length); return out; }, new Uint8Array()); })() : r.take(arg(r, info)) }; if (major === 4) { const items: PlutusData[] = []; const n = info === 31 ? -1 : arg(r, info); if (n < 0) { while (r.bytes[r.pos] !== 255) items.push(read(r)); r.pos++; } else for (let i = 0; i < n; i++) items.push(read(r)); return { kind: "list", value: items }; } if (major === 5) { const pairs: [PlutusData, PlutusData][] = []; const n = info === 31 ? -1 : arg(r, info); if (n < 0) { while (r.bytes[r.pos] !== 255) pairs.push([read(r), read(r)]); r.pos++; } else for (let i = 0; i < n; i++) pairs.push([read(r), read(r)]); return { kind: "map", value: pairs }; } if (major === 6) { const tag = arg(r, info); const body = read(r); if (tag >= 121 && tag <= 127) return constr(tag - 121, body); if (tag >= 1280 && tag <= 1400) return constr(tag - 1273, body); if (tag === 102 && body.kind === "list" && body.value.length === 2 && body.value[0].kind === "int") return constr(body.value[0].value, body.value[1]); } throw new Error("unsupported plutus data"); };
export const decodePlutusData = (hex: string) => { const r = new Reader(hexBytes(hex)); const out = read(r); if (r.pos !== r.bytes.length) throw new Error("trailing cbor"); return out; };
export const bytes = (d: PlutusData, name: string) => { if (d.kind !== "bytes") throw new Error(`${name} is not bytes`); return d.value; };
export const integer = (d: PlutusData, name: string) => { if (d.kind !== "int") throw new Error(`${name} is not an integer`); return d.value; };
export const hex = (d: PlutusData, name: string) => Buffer.from(bytes(d, name)).toString("hex");
