// GENERATED by web/scripts/sync.mjs from router/src/handler.ts. Edit the router, not this copy.
import { readFile, writeFile } from "node:fs/promises";
import { blake2b } from "@noble/hashes/blake2.js";
import sellersSeed from "./sellers.json" with { type: "json" };
import underwriter from "./underwriter.json" with { type: "json" };
import { evaluateRoutes, sellerRisk, type RouteResult, type Seller, type UnderwriterConfig } from "./routes";

let sellerFile: string | URL = new URL("./sellers.json", import.meta.url);
const sellers: Seller[] = structuredClone(sellersSeed as Seller[]);
const underwriterConfig = underwriter as UnderwriterConfig;
const quotes = new Map<string, { result: RouteResult; task: string; serviceType: string; deadline: string }>();
const KOIOS_URL = "https://preprod.koios.rest/api/v1";

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, sortKeys(item)]));
  return value;
}

export function canonicalJson(value: unknown): string { return JSON.stringify(sortKeys(value)); }
export function termsHash(value: unknown): string { return Buffer.from(blake2b(new TextEncoder().encode(canonicalJson(value)), { dkLen: 32 })).toString("hex"); }

export async function useSellersFile(path: string) {
  sellerFile = path;
  sellers.splice(0, sellers.length, ...(JSON.parse(await readFile(path, "utf8")) as Seller[]));
}

async function persistSellers(next: Seller[]) {
  if (process.env.VERCEL) throw new Error("ingest is disabled on this deployment: sellers.json is read-only here, run the local router to record outcomes");
  await writeFile(sellerFile, `${JSON.stringify(next, null, 2)}\n`);
}

type KoiosTx = { tx_hash?: string; inputs?: Array<Record<string, unknown>>; outputs?: Array<Record<string, unknown>> };
const claimVaultAddress = process.env.CLAIM_VAULT_ADDRESS ?? "addr_test1wpvyupyu5rclc55v8j342y295mc8f6wdc434ansa7j64vwc2mvcle";

function hasClaimRedeemer(input: Record<string, unknown>, success: boolean): boolean {
  const redeemer = input.redeemer ?? input.spending_redeemer ?? input.redeemer_data;
  const text = JSON.stringify(redeemer ?? "").toLowerCase();
  if (text.includes(success ? "claim" : "forfeit")) return true;
  const constructor = (redeemer as { constructor?: unknown } | null)?.constructor ?? (redeemer as { value?: { constructor?: unknown } } | null)?.value?.constructor;
  return constructor === (success ? 0 : 1);
}

async function koios<T>(path: string, body: unknown): Promise<T> {
  const key = process.env.KAIOS_KEY;
  if (!key) throw new Error("KAIOS_KEY is not set");
  const response = await fetch(`${KOIOS_URL}/${path}`, {
    method: "POST",
    headers: { authorization: `Bearer ${key}`, "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!response.ok) throw new Error(`Koios ${path} returned ${response.status}`);
  return await response.json() as T;
}

async function requireConfirmedTx(txHash: string, seller: Seller, success: boolean, paymentTxHash?: string): Promise<void> {
  if (!/^[0-9a-f]{64}$/i.test(txHash)) throw new Error("txHash must be a 64-character hex hash");
  const rows = await koios<Array<{ num_confirmations?: number | null; status?: string }>>("tx_status", { _tx_hashes: [txHash] });
  const row = rows[0];
  if (row?.status && /fail|reject|invalid/i.test(row.status)) throw new Error(`transaction rejected: ${row.status}`);
  if ((row?.num_confirmations ?? 0) < 1) throw new Error("txHash is not confirmed");
  const txRows = await koios<KoiosTx[]>("tx_info", { _tx_hashes: [txHash], _bytecode: true });
  const tx = txRows[0];
  const scriptHash = process.env.CLAIM_VAULT_SCRIPT_HASH;
  const claimInput = tx?.inputs?.find((input) => (input.address === claimVaultAddress || (scriptHash && input.script_hash === scriptHash)) && hasClaimRedeemer(input, success));
  if (!claimInput) throw new Error("transaction does not spend the claim vault with the expected redeemer");
  const paymentHash = paymentTxHash ?? txHash;
  if (!/^[0-9a-f]{64}$/i.test(paymentHash)) throw new Error("paymentTxHash must be a 64-character hex hash");
  if (paymentHash !== txHash) {
    const paymentStatus = (await koios<Array<{ num_confirmations?: number | null }>>("tx_status", { _tx_hashes: [paymentHash] }))[0];
    if ((paymentStatus?.num_confirmations ?? 0) < 1) throw new Error("paymentTxHash is not confirmed");
  }
  const payment = paymentHash === txHash ? tx : (await koios<KoiosTx[]>("tx_info", { _tx_hashes: [paymentHash], _bytecode: true }))[0];
  if (!payment?.outputs?.some((output) => {
    const value = output.value as { lovelace?: number | string } | undefined;
    return output.address === seller.payTo && Number(value?.lovelace ?? 0) > 0;
  })) throw new Error("transaction does not pay the seller");
}

export async function ingestOutcome(sellerId: string, success: boolean, txHash: string): Promise<Seller> {
  if (!txHash || /\s/.test(txHash)) throw new Error("txHash is required");
  const index = sellers.findIndex((item) => item.id === sellerId);
  if (index < 0) throw new Error("seller not found");
  const updated = structuredClone(sellers[index]);
  if (success) updated.successes += 1; else updated.failures += 1;
  updated.evidence.push(txHash);
  const next = sellers.map((item, i) => (i === index ? updated : item));
  await persistSellers(next);
  sellers[index] = updated;
  return structuredClone(updated);
}

function json(data: unknown, status = 200): Response { return new Response(data === null ? null : JSON.stringify(data), { status, headers: { "content-type": "application/json", "access-control-allow-origin": "*", "access-control-allow-methods": "GET,POST,OPTIONS", "access-control-allow-headers": "content-type" } }); }
function selectedTerms(result: RouteResult) { const route = result.routes.find((item) => item.route === result.selectedRoute && item.sellers.join(",") === result.selectedSellers.join(",")); return { route: result.selectedRoute, sellers: result.selectedSellers, servicePriceAda: route?.servicePriceAda, premiumAda: route?.premiumAda, coverageAda: route?.coverageAda }; }

export async function handle(request: Request, pathname = new URL(request.url).pathname): Promise<Response> {
  if (request.method === "OPTIONS") return json(null, 204);
  try {
    if (request.method === "GET" && pathname === "/health") return json({ ok: true });
    if (request.method === "GET" && pathname === "/sellers") return json(sellers.map((seller) => ({ ...seller, risk: sellerRisk(seller, underwriterConfig) })));
    if (request.method === "GET" && pathname.startsWith("/quotes/")) {
      const id = decodeURIComponent(pathname.slice("/quotes/".length));
      const saved = quotes.get(id);
      const seller = sellers.find((item) => item.id === id);
      if (!saved && !seller) return json({ error: "quote not found" }, 404);
      if (seller) {
        const risk = sellerRisk(seller, underwriterConfig);
        const coverageLimitAda = underwriterConfig.coverageLimitAda;
        const premiumAda = risk.pClaim * coverageLimitAda + underwriterConfig.capitalCostRate * coverageLimitAda + underwriterConfig.fraudRiskAda + underwriterConfig.correlationRiskAda + underwriterConfig.marginAda;
        return json({ seller: seller.id, risk, coverageOffers: [{ underwriter: underwriterConfig.underwriter, premiumAda, coverageLimitAda, deductibleAda: underwriterConfig.deductibleAda, collateralRef: underwriterConfig.collateralRef, termsHash: termsHash({ seller: seller.id, coverageLimitAda, deductibleAda: underwriterConfig.deductibleAda }) }] });
      }
      return json({ ...saved, termsHash: termsHash(selectedTerms(saved!.result)) });
    }
    if (request.method === "POST" && pathname === "/ingest") {
      const body = await request.json() as { sellerId?: unknown; success?: unknown; txHash?: unknown; paymentTxHash?: unknown };
      if (typeof body.sellerId !== "string" || typeof body.success !== "boolean" || typeof body.txHash !== "string") return json({ error: "sellerId, success, and txHash are required" }, 400);
      const token = process.env.INGEST_TOKEN;
      if (!token || request.headers.get("authorization") !== `Bearer ${token}`) return json({ error: "ingest authentication required" }, 401);
      const seller = sellers.find((item) => item.id === body.sellerId);
      if (!seller) return json({ error: "seller not found" }, 400);
      const paymentTxHash = body.paymentTxHash === undefined ? undefined : typeof body.paymentTxHash === "string" ? body.paymentTxHash : "";
      await requireConfirmedTx(body.txHash, seller, body.success, paymentTxHash);
      if (seller.evidence.includes(body.txHash)) return json(seller);
      return json(await ingestOutcome(body.sellerId, body.success, body.txHash));
    }
    if (request.method === "POST" && pathname === "/best-route") {
      const body = await request.json() as { task: string; serviceType: string; deadline: string; downstreamLossAda: number; riskAversion?: number; sharedInfrastructure?: boolean; candidateSellers: string[]; constraints?: Parameters<typeof evaluateRoutes>[0]["constraints"] };
      const candidates = body.candidateSellers.flatMap((id) => {
        const exact = sellers.find((seller) => seller.id === id);
        return exact ? [exact] : sellers.filter((seller) => seller.provider === id);
      });
      if (candidates.some((seller) => !seller)) return json({ error: "unknown seller" }, 400);
      if (candidates.length === 0) return json({ error: "unknown seller" }, 400);
      const result = evaluateRoutes({ downstreamLossAda: body.downstreamLossAda, riskAversion: body.riskAversion, sharedInfrastructure: body.sharedInfrastructure, candidateSellers: candidates as Seller[], constraints: body.constraints, underwriter: underwriterConfig });
      const quoteId = crypto.randomUUID();
      quotes.set(quoteId, { result, task: body.task, serviceType: body.serviceType, deadline: body.deadline });
      return json({ ...result, quoteId, termsHash: termsHash(selectedTerms(result)) });
    }
    return json({ error: "not found" }, 404);
  } catch (error) { return json({ error: error instanceof Error ? error.message : "request failed" }, 400); }
}
