// GENERATED by web/scripts/sync.mjs from router/src/risk.ts. Edit the router, not this copy.
export const DEFAULT_ALPHA0 = 2;
export const DEFAULT_BETA0 = 8;
export const DEFAULT_APPLICABILITY = 0.8;

export type RiskOptions = {
  dependencyRiskPenalty?: number;
  recentIncidentPenalty?: number;
  bondDiscount?: number;
  coverageApplicabilityRate?: number;
};

export type Risk = {
  alpha0: number;
  beta0: number;
  alpha: number;
  beta: number;
  posterior: number;
  pLoss: number;
  pClaim: number;
  confidence: number;
  dependencyRiskPenalty: number;
  recentIncidentPenalty: number;
  bondDiscount: number;
  coverageApplicabilityRate: number;
};

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

export function betaBinomialRisk(successes: number, failures: number, options: RiskOptions = {}): Risk {
  if (!Number.isInteger(successes) || successes < 0 || !Number.isInteger(failures) || failures < 0) {
    throw new Error("successes and failures must be non-negative integers");
  }
  const dependencyRiskPenalty = options.dependencyRiskPenalty ?? 0;
  const recentIncidentPenalty = options.recentIncidentPenalty ?? 0;
  const bondDiscount = options.bondDiscount ?? 0;
  const coverageApplicabilityRate = options.coverageApplicabilityRate ?? DEFAULT_APPLICABILITY;
  const alpha = DEFAULT_ALPHA0 + failures;
  const beta = DEFAULT_BETA0 + successes;
  const posterior = alpha / (alpha + beta);
  const pLoss = clamp(posterior + dependencyRiskPenalty + recentIncidentPenalty - bondDiscount, 0.001, 0.999);
  return {
    alpha0: DEFAULT_ALPHA0,
    beta0: DEFAULT_BETA0,
    alpha,
    beta,
    posterior,
    pLoss,
    pClaim: pLoss * coverageApplicabilityRate,
    confidence: alpha + beta,
    dependencyRiskPenalty,
    recentIncidentPenalty,
    bondDiscount,
    coverageApplicabilityRate,
  };
}
