// Generates lib/cot/vectors.ak: genuine secp256k1 signatures over CRE-shaped reports.
// Run from onchain/scripts: npm ci && node generate_vectors.mjs
// Keys are derived from public labels. They are test keys that guard nothing.
import { writeFile } from 'node:fs/promises';
import { secp256k1 } from '@noble/curves/secp256k1';
import { keccak_256 } from '@noble/hashes/sha3';
import { blake2b } from '@noble/hashes/blake2b';

const hex = (b) => `#"${Buffer.from(b).toString('hex')}"`;
const cat = (...p) => Uint8Array.from(Buffer.concat(p.map((x) => Buffer.from(x))));
const fill = (n, v) => new Uint8Array(n).fill(v);
const ascii = (s) => Uint8Array.from(Buffer.from(s));

const F = 1;
const keyFor = (label) => keccak_256(ascii(`cost-of-trust test signer ${label}`));
const privs = [0, 1, 2, 3].map((i) => keyFor(`don-${i}`));
const outsider = keyFor('outsider');
const pub64 = (priv) => secp256k1.getPublicKey(priv, false).slice(1);
const addr20 = (pk) => keccak_256(pk).slice(12);

const owner = Uint8Array.from(Buffer.from('00112233445566778899aabbccddeeff00112233', 'hex'));
const name = ascii('trustflow1');
const cid = keccak_256(ascii('cost-of-trust workflow cid'));
const termsHash = keccak_256(ascii('cost-of-trust terms'));
const otherTermsHash = keccak_256(ascii('cost-of-trust other terms'));
const coverageTx = Uint8Array.from(Buffer.from('11'.repeat(32), 'hex'));
const otherTx = Uint8Array.from(Buffer.from('33'.repeat(32), 'hex'));
const COVERAGE_INDEX = 2;
const taskTx = Uint8Array.from(Buffer.from('77'.repeat(32), 'hex'));
const otherTaskTx = Uint8Array.from(Buffer.from('88'.repeat(32), 'hex'));
const TASK_INDEX = 1;

const signers = privs.map((p) => addr20(pub64(p)));

const donConfigDigest = keccak_256(ascii('cost-of-trust ocr config digest'));

// config digest, mirrored by lib/cot/model.ak config_digest
const digest = Buffer.from(
  blake2b(cat(Uint8Array.of(F), owner, name, cid, donConfigDigest, Uint8Array.of(signers.length), ...signers), { dkLen: 32 }),
);

const header = (wfName) =>
  cat(Uint8Array.of(1), fill(32, 0xaa), fill(4, 0), fill(4, 0), fill(4, 0), cid, wfName, owner, Uint8Array.of(0, 0));
const body = (terms, decision, tx, index, task, taskIndex) =>
  cat(terms, Uint8Array.of(decision), tx, Uint8Array.of(index >> 8, index & 255), task, Uint8Array.of(taskIndex >> 8, taskIndex & 255));
const report = (o) =>
  cat(header(o.name ?? name), body(o.terms ?? termsHash, o.decision, o.tx ?? coverageTx, o.index ?? COVERAGE_INDEX, o.task ?? taskTx, o.taskIndex ?? TASK_INDEX));

// What the DON signs besides the report: OCR config digest(32) ++ seq_nr as a 32-byte big-endian word.
const context = cat(donConfigDigest, fill(31, 0), Uint8Array.of(7));
const contextOther = cat(keccak_256(ascii('cost-of-trust other config digest')), fill(31, 0), Uint8Array.of(7));
const signedDigest = (raw, ctx = context) => keccak_256(cat(keccak_256(raw), ctx));
const sign = (priv, raw, ctx = context) => {
  const sig = secp256k1.sign(signedDigest(raw, ctx), priv, { lowS: true });
  return cat(sig.toCompactRawBytes(), Uint8Array.of(sig.recovery + 27));
};

const reports = {
  failure: report({ decision: 1 }),
  success: report({ decision: 0 }),
  inconclusive: report({ decision: 2 }),
  badDecision: report({ decision: 3 }),
  wrongRef: report({ decision: 1, tx: otherTx }),
  wrongIndex: report({ decision: 1, index: 3 }),
  wrongTerms: report({ decision: 1, terms: otherTermsHash }),
  wrongTask: report({ decision: 1, task: otherTaskTx }),
  wrongTaskIndex: report({ decision: 1, taskIndex: 2 }),
  wrongName: report({ decision: 1, name: ascii('othername1') }),
};
for (const r of Object.values(reports)) if (r.length !== 210) throw new Error('report length');

const L = (xs) => `[${xs.map(hex).join(', ')}]`;
const pubs = privs.map(pub64);
let out = `//// Generated by scripts/generate_vectors.mjs. Never edit by hand.
//// Four DON signers (f = 1), one outsider key, and reports signed over keccak256(keccak256(raw) ++ context).

pub const owner: ByteArray = ${hex(owner)}

pub const name: ByteArray = ${hex(name)}

pub const cid: ByteArray = ${hex(cid)}

pub const f: Int = ${F}

pub const terms_hash: ByteArray = ${hex(termsHash)}

pub const coverage_tx: ByteArray = ${hex(coverageTx)}

pub const coverage_index: Int = ${COVERAGE_INDEX}

pub const task_tx: ByteArray = ${hex(taskTx)}

pub const task_index: Int = ${TASK_INDEX}

pub const don_config_digest: ByteArray = ${hex(donConfigDigest)}

pub const context: ByteArray = ${hex(context)}

pub const signers: List<ByteArray> = ${L(signers)}

pub const pubkeys: List<ByteArray> = ${L(pubs)}

pub const outsider_pubkey: ByteArray = ${hex(pub64(outsider))}

pub const config_digest: ByteArray = ${hex(digest)}
`;
for (const [k, raw] of Object.entries(reports)) {
  const snake = k.replace(/[A-Z]/g, (c) => '_' + c.toLowerCase());
  out += `\npub const report_${snake}: ByteArray = ${hex(raw)}\n`;
  out += `\npub const sigs_${snake}: List<ByteArray> = ${L(privs.map((p) => sign(p, raw)))}\n`;
}
out += `\npub const outsider_sig_failure: ByteArray = ${hex(sign(outsider, reports.failure))}\n`;
out += `\npub const context_other: ByteArray = ${hex(contextOther)}\n`;
out += `\npub const sigs_failure_other_context: List<ByteArray> = ${L(privs.map((p) => sign(p, reports.failure, contextOther)))}\n`;
await writeFile('../lib/cot/vectors.ak', out);
console.log('wrote ../lib/cot/vectors.ak');
